#spring:
#logging:
#  file: logs/dev_app.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss:SSS} %-5level [%thread] %logger{50}.%M\\(%line\\) : %cyan%msg%n"
#  level:
#    com.lnt: INFO
#  rollingPolicy:
##    fileNamePattern: logs/dev_app.%d{yyyy-MM-dd}.txt
##    maxHistory: 30
#    totalSizeCap: 10